(function() {var implementors = {};
implementors["steed"] = ["impl&lt;T&gt; <a class='trait' href='steed/borrow/trait.Borrow.html' title='steed::borrow::Borrow'>Borrow</a>&lt;T&gt; for <a class='struct' href='steed/boxed/struct.Box.html' title='steed::boxed::Box'>Box</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='steed/marker/trait.Sized.html' title='steed::marker::Sized'>Sized</a></span>","impl&lt;T&gt; <a class='trait' href='steed/borrow/trait.Borrow.html' title='steed::borrow::Borrow'>Borrow</a>&lt;T&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/arc/struct.Arc.html' title='alloc::arc::Arc'>Arc</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='steed/marker/trait.Sized.html' title='steed::marker::Sized'>Sized</a></span>","impl&lt;T&gt; <a class='trait' href='steed/borrow/trait.Borrow.html' title='steed::borrow::Borrow'>Borrow</a>&lt;T&gt; for <a class='struct' href='steed/rc/struct.Rc.html' title='steed::rc::Rc'>Rc</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='steed/marker/trait.Sized.html' title='steed::marker::Sized'>Sized</a></span>","impl&lt;'a, B&gt; <a class='trait' href='steed/borrow/trait.Borrow.html' title='steed::borrow::Borrow'>Borrow</a>&lt;B&gt; for <a class='enum' href='steed/borrow/enum.Cow.html' title='steed::borrow::Cow'>Cow</a>&lt;'a, B&gt; <span class='where'>where B: <a class='trait' href='steed/borrow/trait.ToOwned.html' title='steed::borrow::ToOwned'>ToOwned</a> + ?<a class='trait' href='steed/marker/trait.Sized.html' title='steed::marker::Sized'>Sized</a>, B::<a class='trait' href='steed/borrow/trait.ToOwned.html' title='steed::borrow::ToOwned'>Owned</a>: 'a</span>","impl&lt;T&gt; <a class='trait' href='steed/borrow/trait.Borrow.html' title='steed::borrow::Borrow'>Borrow</a>&lt;[T]&gt; for <a class='struct' href='steed/vec/struct.Vec.html' title='steed::vec::Vec'>Vec</a>&lt;T&gt;","impl <a class='trait' href='steed/borrow/trait.Borrow.html' title='steed::borrow::Borrow'>Borrow</a>&lt;str&gt; for <a class='struct' href='steed/string/struct.String.html' title='steed::string::String'>String</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
