(function() {var implementors = {};
implementors["std"] = ["impl&lt;'a, 'b, T&gt; <a class='trait' href='std/ops/trait.Sub.html' title='std::ops::Sub'>Sub</a>&lt;&amp;'b <a class='struct' href='std/collections/btree_set/struct.BTreeSet.html' title='std::collections::btree_set::BTreeSet'>BTreeSet</a>&lt;T&gt;&gt; for &amp;'a <a class='struct' href='std/collections/btree_set/struct.BTreeSet.html' title='std::collections::btree_set::BTreeSet'>BTreeSet</a>&lt;T&gt; <span class='where'>where T: <a class='trait' href='std/cmp/trait.Ord.html' title='std::cmp::Ord'>Ord</a> + <a class='trait' href='std/clone/trait.Clone.html' title='std::clone::Clone'>Clone</a></span>","impl&lt;E&gt; <a class='trait' href='std/ops/trait.Sub.html' title='std::ops::Sub'>Sub</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/enum_set/struct.EnumSet.html' title='collections::enum_set::EnumSet'>EnumSet</a>&lt;E&gt;&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/collections/enum_set/struct.EnumSet.html' title='collections::enum_set::EnumSet'>EnumSet</a>&lt;E&gt; <span class='where'>where E: <a class='trait' href='https://doc.rust-lang.org/nightly/collections/enum_set/trait.CLike.html' title='collections::enum_set::CLike'>CLike</a></span>","impl <a class='trait' href='std/ops/trait.Sub.html' title='std::ops::Sub'>Sub</a> for <a class='struct' href='std/time/struct.Duration.html' title='std::time::Duration'>Duration</a>","impl <a class='trait' href='std/ops/trait.Sub.html' title='std::ops::Sub'>Sub</a>&lt;<a class='struct' href='std/time/struct.Duration.html' title='std::time::Duration'>Duration</a>&gt; for <a class='struct' href='std/time/struct.Instant.html' title='std::time::Instant'>Instant</a>","impl <a class='trait' href='std/ops/trait.Sub.html' title='std::ops::Sub'>Sub</a>&lt;<a class='struct' href='std/time/struct.Instant.html' title='std::time::Instant'>Instant</a>&gt; for <a class='struct' href='std/time/struct.Instant.html' title='std::time::Instant'>Instant</a>","impl <a class='trait' href='std/ops/trait.Sub.html' title='std::ops::Sub'>Sub</a>&lt;<a class='struct' href='std/time/struct.Duration.html' title='std::time::Duration'>Duration</a>&gt; for <a class='struct' href='std/time/struct.SystemTime.html' title='std::time::SystemTime'>SystemTime</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
